//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce.Modelo_Fisico
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedidos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pedidos()
        {
            this.Produtos = new HashSet<Produtos>();
        }
    
        public int IdPd { get; set; }
        public System.DateTime DataEntrega { get; set; }
        public System.DateTime DataPd { get; set; }
        public string EstadoPd { get; set; }
        public bool TipoPd { get; set; }
        public string MoradaPd { get; set; }
        public float ValorPd { get; set; }
        public string MetodoPag { get; set; }
        public string Clientes_Id { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Produtos> Produtos { get; set; }
    }
}
